### PR TITLE
An initial attempt at making the PSCAN repository binder-compatible.

### PR DESCRIPTION
**Pull request by ctb**
See [mybinder.org](https://mybinder.org).

Because this repository is currently private, binder cannot access it. So I've set up a public repo at https://github.com/ctb/2019-pscan-test that just contains the install stuff, to see if we can install all of the necessary R packages. I'm running it right now so we will see if the necessary R packages can be loaded!

### CODE REVIEW

**Comment by ctb** [comment]
Try it out!

[Binder](https://mybinder.org/v2/gh/SystemsBiologist/PSCAN/binderize?filepath=PSCAN.test.ipynb)

**Comment by ctb** [comment]
On the 3rd cell, I get this error:
```
Error in estimateSizeFactorsForMatrix(countsERCC): could not find function "estimateSizeFactorsForMatrix"
Traceback:

1. NoiseFiltering(Object, percentile, CV, gene_names2, geneCol, 
 .     FgeneCol, erccCol, Val = T)
```
any idea?

also I would suggest reorganizing the notebook so that the "do not execute this by default!" cells are either at the bottom, or placed inside of an 'if False:' block, so that people can execute the entire notebook all in one go.

**Comment by SystemsBiologist** [comment]
I am not sure about the reason for that error since the function "estimateSizeFactorsForMatrix" is in the DESeq2 package, which is one of the required packages!

**Comment by SystemsBiologist** [comment]
estimateSizeFactorsForMatrix = function (counts, locfunc = median) {
+     loggeomeans <- rowMeans(log(counts))
+     apply(counts, 2, function(cnts) exp(locfunc((log(cnts) -
+         loggeomeans)[is.finite(loggeomeans)])))
+ }

What about including this function in the PSCAN_class.R?

**Comment by SystemsBiologist** [comment]
estimateSizeFactorsForMatrix = function (counts, locfunc = median){
	loggeomeans <- rowMeans(log(counts))
	apply(counts, 2, function(cnts) exp(locfunc((log(cnts) - loggeomeans)[is.finite(loggeomeans)])))
}

What about including this function in the PSCAN_class.R?
I tested in R that function without having the DESeq2 package and it worked

**Comment by SystemsBiologist** [comment]
I think the reason of the error is that some packages are not loaded, here is the output of running the required packages cell:
there is no package called ‘TSCAN’
there is no package called ‘genefilter’
there is no package called ‘DESeq2’
there is no package called ‘biomaRt’
there is no package called ‘RWeka’
there is no package called ‘samr’

**Pull request merged**
